version: "3"

services:
  tikva-node:
    build: ../tikva-node
    image: tikva-node
    command: tail -f /dev/null
    hostname: tikva-node
    volumes:
      - ../..:/opt/tikva
    working_dir: /opt/tikva
    ports:
      - "3000:3000"
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:latest
    networks:
      - back-tier

  mongo:
    image: mongo:latest
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: